import type { AnalysisResult, Endpoint, ParamInfo } from "../types";
import { tryParseJson, inferJsonSchema } from "../inference";

interface OpenApiParam {
  name: string;
  in: "path" | "query" | "header";
  required: boolean;
  schema: { type: string };
  examples?: Record<string, { value: string }>;
}

function toSchemaType(type: string): string {
  if (["integer", "number", "boolean", "string", "array", "object", "null"].includes(type)) {
    return type;
  }
  return "string";
}

function buildParameters(params: ParamInfo[]): OpenApiParam[] {
  const out: OpenApiParam[] = [];
  for (const p of params) {
    if (p.in === "body") {
      continue;
    }
    const param: OpenApiParam = {
      name: p.name,
      in: p.in,
      required: p.in === "path" ? true : p.required,
      schema: { type: toSchemaType(p.type) }
    };
    if (p.examples.length > 0) {
      param.examples = {};
      p.examples.forEach((ex, i) => {
        param.examples![`example${i + 1}`] = { value: ex };
      });
    }
    out.push(param);
  }
  return out;
}

function buildRequestBody(ep: Endpoint): unknown | undefined {
  if (ep.sampleRequestBody) {
    const parsed = tryParseJson(ep.sampleRequestBody);
    if (parsed !== undefined) {
      return {
        content: {
          "application/json": {
            schema: inferJsonSchema(parsed),
            example: parsed
          }
        }
      };
    }
  }
  const bodyParams = ep.params.filter((p) => p.in === "body");
  if (bodyParams.length === 0) {
    return undefined;
  }
  const properties: Record<string, { type: string }> = {};
  for (const p of bodyParams) {
    properties[p.name] = { type: toSchemaType(p.type) };
  }
  return {
    content: {
      "application/json": {
        schema: { type: "object", properties }
      }
    }
  };
}

function buildResponses(ep: Endpoint): Record<string, unknown> {
  const responses: Record<string, unknown> = {};
  const statuses = ep.statuses.length > 0 ? ep.statuses : [200];
  for (const status of statuses) {
    const entry: Record<string, unknown> = {
      description: `Observed response (${status})`
    };
    if (ep.sampleResponse) {
      const parsed = tryParseJson(ep.sampleResponse);
      if (parsed !== undefined) {
        entry.content = {
          "application/json": {
            schema: inferJsonSchema(parsed),
            example: parsed
          }
        };
      }
    }
    responses[String(status)] = entry;
  }
  return responses;
}

/** Generate an OpenAPI 3.1 document from analysis results. */
export function generateOpenApi(result: AnalysisResult): Record<string, unknown> {
  const origins = Array.from(new Set(result.endpoints.map((e) => e.origin)));
  const paths: Record<string, Record<string, unknown>> = {};

  for (const ep of result.endpoints) {
    if (ep.kind === "websocket") {
      continue;
    }
    const pathKey = ep.pathTemplate || "/";
    const pathItem = paths[pathKey] ?? (paths[pathKey] = {});
    const methods = ep.methods.length > 0 ? ep.methods : ["GET"];
    for (const method of methods) {
      const op: Record<string, unknown> = {
        summary: `${method} ${ep.pathTemplate}`,
        tags: [ep.host],
        parameters: buildParameters(ep.params),
        responses: buildResponses(ep)
      };
      if (ep.kind === "graphql" && ep.graphqlOperations?.length) {
        op.description = `GraphQL operations: ${ep.graphqlOperations.join(", ")}`;
      }
      const requestBody = buildRequestBody(ep);
      if (requestBody && method !== "GET" && method !== "HEAD") {
        op.requestBody = requestBody;
      }
      pathItem[method.toLowerCase()] = op;
    }
  }

  return {
    openapi: "3.1.0",
    info: {
      title: `APIScraper – ${hostOf(result.startUrl)}`,
      version: "1.0.0",
      description:
        `Auto-generated by APIScraper from ${result.startUrl} on ${result.startedAt}. ` +
        `${result.endpoints.length} endpoint(s) discovered.`
    },
    servers: origins.map((url) => ({ url })),
    paths
  };
}

function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}
